/**
 * PDF export template for Preview Plans.
 *
 * Uses @react-pdf/renderer (pure JS — no binary deps, safe for Firebase
 * Cloud Functions). The layout mirrors the markdown export structure
 * with styled section cards.
 */
import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from "@react-pdf/renderer";
import type { PreviewPlan } from "@/types/preview-plan";

const colors = {
  primary: "#3B5929",
  accent: "#748848",
  bg: "#FAFAF5",
  card: "#F4F1E8",
  border: "#D5DCC8",
  text: "#1D2418",
  muted: "#596351",
  white: "#FFFFFF",
  red: "#DC2626",
  yellow: "#D97706",
  green: "#16A34A",
};

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: "Helvetica",
    fontSize: 10,
    color: colors.text,
    backgroundColor: colors.bg,
  },
  header: {
    marginBottom: 20,
    borderBottom: `2px solid ${colors.primary}`,
    paddingBottom: 12,
  },
  title: {
    fontSize: 22,
    fontWeight: "bold",
    color: colors.primary,
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 10,
    color: colors.muted,
  },
  section: {
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "bold",
    color: colors.primary,
    marginBottom: 6,
    borderBottom: `1px solid ${colors.border}`,
    paddingBottom: 4,
  },
  card: {
    backgroundColor: colors.card,
    borderRadius: 4,
    padding: 10,
    marginBottom: 8,
  },
  label: {
    fontSize: 8,
    fontWeight: "bold",
    color: colors.accent,
    textTransform: "uppercase" as const,
    marginBottom: 3,
  },
  body: {
    fontSize: 10,
    lineHeight: 1.5,
    color: colors.text,
  },
  listItem: {
    fontSize: 10,
    lineHeight: 1.5,
    marginBottom: 2,
    paddingLeft: 8,
  },
  stageRow: {
    flexDirection: "row" as const,
    borderBottom: `1px solid ${colors.border}`,
    paddingVertical: 4,
  },
  stageCell: {
    flex: 1,
    fontSize: 9,
    paddingRight: 6,
  },
  stageCellBold: {
    flex: 1,
    fontSize: 9,
    fontWeight: "bold",
    paddingRight: 6,
  },
  priorityBadge: {
    fontSize: 8,
    fontWeight: "bold",
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 2,
  },
  footer: {
    position: "absolute" as const,
    bottom: 20,
    left: 40,
    right: 40,
    fontSize: 8,
    color: colors.muted,
    textAlign: "center" as const,
    borderTop: `1px solid ${colors.border}`,
    paddingTop: 8,
  },
});

function priorityColor(p: string) {
  return p === "high" ? colors.red : p === "medium" ? colors.yellow : colors.green;
}

export function PlanPDFDocument({ plan }: { plan: PreviewPlan }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.title}>Preview Plan</Text>
          <Text style={styles.subtitle}>
            Generated by Nicer Systems — nicersystems.com
          </Text>
        </View>

        {/* Executive Summary */}
        {plan.ops_pulse?.executive_summary && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Executive Summary</Text>
            <View style={styles.card}>
              {plan.ops_pulse.executive_summary.problem && (
                <View style={{ marginBottom: 6 }}>
                  <Text style={styles.label}>Problem</Text>
                  <Text style={styles.body}>
                    {plan.ops_pulse.executive_summary.problem}
                  </Text>
                </View>
              )}
              {plan.ops_pulse.executive_summary.solution && (
                <View style={{ marginBottom: 6 }}>
                  <Text style={styles.label}>Solution</Text>
                  <Text style={styles.body}>
                    {plan.ops_pulse.executive_summary.solution}
                  </Text>
                </View>
              )}
              {plan.ops_pulse.executive_summary.impact && (
                <View style={{ marginBottom: 6 }}>
                  <Text style={styles.label}>Impact</Text>
                  <Text style={styles.body}>
                    {plan.ops_pulse.executive_summary.impact}
                  </Text>
                </View>
              )}
            </View>
          </View>
        )}

        {/* Scope */}
        {plan.intake?.suggested_scope && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Suggested Scope</Text>
            <Text style={styles.body}>{plan.intake.suggested_scope}</Text>
            {plan.intake.clarified_problem && (
              <View style={{ marginTop: 6 }}>
                <Text style={styles.label}>Clarified Problem</Text>
                <Text style={styles.body}>
                  {plan.intake.clarified_problem}
                </Text>
              </View>
            )}
          </View>
        )}

        {/* Workflow Stages */}
        {plan.workflow?.stages?.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>
              Workflow Map ({plan.workflow.stages.length} stages)
            </Text>
            {/* Table header */}
            <View style={[styles.stageRow, { backgroundColor: colors.card }]}>
              <Text style={styles.stageCellBold}>Stage</Text>
              <Text style={styles.stageCellBold}>Owner</Text>
              <Text style={styles.stageCellBold}>Entry Criteria</Text>
              <Text style={styles.stageCellBold}>Exit Criteria</Text>
            </View>
            {plan.workflow.stages.map((s, i) => (
              <View key={i} style={styles.stageRow}>
                <Text style={styles.stageCellBold}>{s.name}</Text>
                <Text style={styles.stageCell}>{s.owner_role}</Text>
                <Text style={styles.stageCell}>{s.entry_criteria}</Text>
                <Text style={styles.stageCell}>{s.exit_criteria}</Text>
              </View>
            ))}
          </View>
        )}

        {/* KPIs */}
        {plan.dashboard?.kpis?.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>KPIs</Text>
            {plan.dashboard.kpis.map((k, i) => (
              <View key={i} style={styles.card}>
                <Text style={styles.label}>{k.name}</Text>
                <Text style={styles.body}>{k.definition}</Text>
                {k.why_it_matters && (
                  <Text style={[styles.body, { color: colors.muted, marginTop: 2 }]}>
                    Why: {k.why_it_matters}
                  </Text>
                )}
              </View>
            ))}
          </View>
        )}

        {/* Automations */}
        {plan.automation?.automations?.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Automations</Text>
            {plan.automation.automations.map((a, i) => (
              <View key={i} style={styles.card}>
                <Text style={styles.label}>Trigger: {a.trigger}</Text>
                <Text style={styles.body}>
                  Steps: {a.steps.join(" → ")}
                </Text>
              </View>
            ))}
          </View>
        )}

        {/* Actions */}
        {plan.ops_pulse?.actions?.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Actions</Text>
            {plan.ops_pulse.actions.map((a, i) => (
              <View key={i} style={{ flexDirection: "row", marginBottom: 4 }}>
                <Text
                  style={[
                    styles.priorityBadge,
                    { color: priorityColor(a.priority) },
                  ]}
                >
                  [{a.priority}]
                </Text>
                <Text style={[styles.body, { flex: 1, marginLeft: 6 }]}>
                  {a.owner_role}: {a.action}
                </Text>
              </View>
            ))}
          </View>
        )}

        {/* Footer */}
        <Text style={styles.footer} fixed>
          This is a draft preview — not a final recommendation. Generated by
          Nicer Systems (nicersystems.com)
        </Text>
      </Page>

      {/* Page 2: Roadmap (if present) */}
      {plan.roadmap && plan.roadmap.phases.length > 0 && (
        <Page size="A4" style={styles.page}>
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>
              Implementation Roadmap ({plan.roadmap.total_estimated_weeks}{" "}
              weeks)
            </Text>
            {plan.roadmap.phases.map((p, i) => (
              <View key={i} style={styles.card}>
                <Text style={styles.label}>
                  Week {p.week}: {p.title}
                </Text>
                {p.tasks.map((t, j) => (
                  <Text key={j} style={styles.listItem}>
                    • [{t.effort}] {t.owner_role}: {t.task}
                  </Text>
                ))}
                {p.quick_wins.length > 0 && (
                  <Text
                    style={[styles.body, { marginTop: 4, color: colors.green }]}
                  >
                    Quick wins: {p.quick_wins.join("; ")}
                  </Text>
                )}
              </View>
            ))}
            <Text style={[styles.body, { marginTop: 8 }]}>
              Critical Path: {plan.roadmap.critical_path}
            </Text>
          </View>

          {/* Proposal (if present) */}
          {plan.proposal && (
            <View style={styles.section}>
              <Text style={styles.sectionTitle}>Executive Proposal</Text>
              {plan.proposal.executive_pitch && (
                <Text style={[styles.body, { marginBottom: 8 }]}>
                  {plan.proposal.executive_pitch}
                </Text>
              )}
              {plan.proposal.value_propositions?.length > 0 && (
                <View style={{ marginBottom: 8 }}>
                  <Text style={styles.label}>Value Propositions</Text>
                  {plan.proposal.value_propositions.map((vp, i) => (
                    <View key={i} style={styles.card}>
                      <Text style={[styles.body, { fontWeight: "bold" }]}>
                        {vp.claim}
                      </Text>
                      <Text style={styles.body}>{vp.evidence}</Text>
                      <Text style={[styles.body, { color: colors.accent }]}>
                        Metric: {vp.metric}
                      </Text>
                    </View>
                  ))}
                </View>
              )}
              {plan.proposal.estimated_roi && (
                <View>
                  <Text style={styles.label}>Estimated ROI</Text>
                  <Text style={styles.body}>
                    {plan.proposal.estimated_roi}
                  </Text>
                </View>
              )}
            </View>
          )}

          <Text style={styles.footer} fixed>
            This is a draft preview — not a final recommendation. Generated by
            Nicer Systems (nicersystems.com)
          </Text>
        </Page>
      )}
    </Document>
  );
}
